/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Katiuska Marin Suarez
 * @author Darwin Guaman Pacalla
 * @author Kleber Avelino Mosquera
 * 
 * usuarios web: 
 * abel:123456 (admin)
 * comprador:12345
 * vendedor:12345
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form jfLoguin
     */
    public FrmLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoguin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtusuario = new javax.swing.JEditorPane();
        jpPassword = new javax.swing.JPasswordField();
        btnNuevoUser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnDemo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnLoguin.setText("Login");
        btnLoguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoguinActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuario");
        jLabel1.setAlignmentY(0.3F);

        jLabel2.setText("Contraseña");

        jScrollPane1.setViewportView(txtusuario);

        btnNuevoUser.setText("Nuevo usuario");
        btnNuevoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Venta de Autos");

        btnDemo.setText("Cargar DEMO");
        btnDemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnNuevoUser)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jpPassword))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDemo)
                            .addComponent(btnLoguin))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoguin)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDemo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoguinActionPerformed
        Usuario u = new Usuario(txtusuario.getText(), String.valueOf(jpPassword.getPassword()));   
        if(usuarioAutorizado(u))
        {
            Oferta.Llenalista();
            Auto.LlenarLista();
            u.setClave(null);
            if (u.getRol().equalsIgnoreCase("comprador")) {
                FrmComprador frm = new FrmComprador();
                frm.setVisible(true);
            }else if (u.getRol().equalsIgnoreCase("vendedor")) {
                FrmVendedor frm = new FrmVendedor();
                frm.setVisible(true);
            }else{
                FrmComprador frm = new FrmComprador();
                frm.setVisible(true);
                FrmVendedor frm2 = new FrmVendedor();
                frm2.setVisible(true);
            }
            dispose();
        }
        else
            JOptionPane.showMessageDialog(this,
                "usuario incorrecto",
                "loguin",
                JOptionPane.ERROR_MESSAGE);
        txtusuario.setFocusable(true);
    }//GEN-LAST:event_btnLoguinActionPerformed

    private void btnNuevoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUserActionPerformed
        FrmUsuarios frm = new FrmUsuarios();
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoUserActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Oferta.GuardarDatos();
        Auto.GuardarDatos();
        System.out.println("Terminando");
    }//GEN-LAST:event_formWindowClosing

    private void btnDemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemoActionPerformed
        Auto a = new Auto("GBN1177", "Chevrolet", "Spark", 1.5, 2017, "n", 300, "verde", "gasolina", "manuales", "automatica", 14.0510, "ChevroletSpark.jpg");
        Auto b = new Auto("GHK1249", "Honda", "sedan", 2.4, 2017, "n", 100, "negro", "gasolina", "Electricos", "automatica", 20.1520, "HondaAccordSedan.png");
        Auto.LAutos.addFirst(a);
        Auto.LAutos.addFirst(b);
        
        Oferta o = new Oferta("GBN1177", "alguien@tes1.com", 11.000);
        Oferta p = new Oferta("GBN1177", "alguien@tes1.com", 10.000);
        Oferta q = new Oferta("GHK1249", "alguien@tes1.com", 14.900);
        Oferta.LOfertas.addFirst(o);
        Oferta.LOfertas.addFirst(p);
        Oferta.LOfertas.addFirst(q);        
    }//GEN-LAST:event_btnDemoActionPerformed

    private Connection con;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDemo;
    private javax.swing.JButton btnLoguin;
    private javax.swing.JButton btnNuevoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JEditorPane txtusuario;
    // End of variables declaration//GEN-END:variables

    private boolean usuarioAutorizado(Usuario _usuario) {
        if (ValidarCampos(_usuario)) {
           ResultSet rs=null;                       
            PreparedStatement st=null;
            try
            {   
                con = Conexion.Conexion.conectar();
                st = con.prepareStatement("SELECT * FROM usuarios WHERE usuario = ? and clave = ? and estado = ?");            
                st.setString(1,_usuario.getUsuario()); 
                st.setString(2, _usuario.getClave());
                st.setString(3, "activo");
                rs = st.executeQuery(); 
                if(rs.next()){
                    _usuario.setRol(rs.getString("rol"));                
                    return true;
                }   
                return false;
            }        
            catch(Exception e){
                System.out.println("Error en la consulta de usuario. \n"+e);            
                return false;
            } finally{
                if ( con!=null) {
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        //Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (st!=null) {
                    try{
                        st.close();
                    }catch (SQLException ex) {
                       // Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                if (rs!= null) {
                    try{
                        rs.close();
                    }catch (SQLException ex) {
                        //Logger.getLogger(FrmIngresarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } 
        }
        
        JOptionPane.showMessageDialog(this,
                "Los datos no son válidos",
                "Login",
                JOptionPane.ERROR_MESSAGE);
        return false;
    }

    //funcion que verifica si los campos tienen datos validos antes de enviar los datos a la base de datos
    private boolean ValidarCampos(Usuario _usuario) {
        if (_usuario.getUsuario().isEmpty()) {
            return false;
        }else if (_usuario.getClave().isEmpty()) {
            return false;
        }
        return true;
    }
}
